
/* Data */
export const SET_FETCH_ALL_USER_ADMIN = "SET_FETCH_ALL_USER_ADMIN";
export const SET_FETCH_DETAIL_USER_ADMIN = "SET_FETCH_DETAIL_USER_ADMIN";
export const SET_FETCH_ALL_CANDIDATEPROFILE_ADMIN =
  "SET_FETCH_ALL_CANDIDATEPROFILE_ADMIN";
export const SET_FETCH_DETAIL_CANDIDATEPROFILE_ADMIN =
  "SET_FETCH_DETAIL_CANDIDATEPROFILE_ADMIN";


/* Chức năng */
export const SET_LOCK_USER = "SET_LOCK_USER";
export const SET_ACTIVATE_USER = "SET_ACTIVATE_USER";
export const SET_ACCEPTED_CANDIDATEPROFILE = "SET_ACCEPTED_CANDIDATEPROFILE";
export const SET_REJECTED_CANDIDATEPROFILE = "SET_REJECTED_CANDIDATEPROFILE";
export const SET_CREATE_NEW_POST = "SET_CREATE_NEW_POST";
export const SET_DELETE_POST = "SET_DELETE_POST";
export const SET_UPDATE_POST = "SET_UPDATE_POST";
