export const SET_FETCH_DETAIL_CANDIDATEPROFILE =
  "SET_FETCH_DETAIL_CANDIDATEPROFILE";
export const SET_FETCH_ALL_CANDIDATEPROFILE = "SET_FETCH_ALL_CANDIDATEPROFILE";

export const SET_CREATE_NEW_CANDIDATEPROFILE =
  "SET_CREATE_NEW_CANDIDATEPROFILE";
