/* Data */
export const SET_FETCH_DETAIL_CANDIDATEPROFILE_USER =
  "SET_FETCH_DETAIL_CANDIDATEPROFILE_USER";
export const SET_FETCH_ALL_CANDIDATEPROFILE_USER =
  "SET_FETCH_ALL_CANDIDATEPROFILE_USER";

/* Chức năng */
export const SET_CREATE_NEW_CANDIDATEPROFILE =
  "SET_CREATE_NEW_CANDIDATEPROFILE";
