export const SET_GET_DETAIL_CANDIDATEPROFILE =
  "SET_GET_DETAIL_CANDIDATEPROFILE";
export const SET_GET_ALL_CANDIDATEPROFILE = "SET_GET_ALL_CANDIDATEPROFILE";

export const SET_CREATE_NEW_CANDIDATEPROFILE =
  "SET_CREATE_NEW_CANDIDATEPROFILE";
